{% set name = "umarkdown" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3cf38cd5d5b81f92fd107fbcebf18eab9e7f983072543f16debcf6f1956161c

build:
  number: 2
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cmake
    - setuptools_scm
    - wheel
  run:
    - python

test:
  imports:
    - umarkdown
    - umarkdown._internal

about:
  home: https://github.com/kumaraditya303/umarkdown
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python wrapper of Markdown using CMark.
  description: |
    Ultra Markdown, an ultra fast (high performance) Markdown 
    parser compliant with the markdown spec written in pure C 
    with bindings for Python 3.7+. Unlike others, Ultra Markdown 
    is written using Python's C API and uses CMark, an ultra fast 
    Markdown parser written in C.
  doc_url: https://umarkdown.netlify.app/
  dev_url: https://github.com/kumaraditya303/umarkdown/

extra:
  recipe-maintainers:
    - kumaraditya303
